---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: customers-query-ce-dispatcher
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: customers-query-ce-dispatcher
  template:
    metadata:
      labels:
        app: customers-query-ce-dispatcher
    spec:
      imagePullSecrets:
        - name: ghcr
      volumes:
        - name: subscriptions-config-volume
          configMap:
            name: customers-query-subscriptions-config
      containers:
        - name: ce-dispatcher
          image: ghcr.io/manuelottlik/htp-cloudevents-poc-ce-dispatcher
          imagePullPolicy: Always
          resources:
            limits:
              memory: 64Mi
              cpu: 50m
          volumeMounts:
            - name: subscriptions-config-volume
              mountPath: /etc/config
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: nats-url
            - name: TARGET_URL
              valueFrom:
                configMapKeyRef:
                  name: customers-query-subscriptions-config
                  key: target-url

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-query-subscriptions-config
data:
  target-url: http://customers-query-service:8081
  subscriptions.yml: |
    - path: /relations/assets/created
      subject: "evt.htp.re.assets.created"
      consumer: customers-query-assets-created

    - path: /relations/assets/updated
      subject: "evt.htp.re.assets.updated"
      consumer: customers-query-assets-updated

    - path: /relations/assets/deleted
      subject: "evt.htp.re.assets.deleted"
      consumer: customers-query-assets-deleted



    - path: /relations/accounts/created
      subject: "evt.htp.re.accounts.created"
      consumer: customers-query-accounts-created

    - path: /relations/accounts/updated
      subject: "evt.htp.re.accounts.updated"
      consumer: customers-query-accounts-updated

    - path: /relations/accounts/deleted
      subject: "evt.htp.re.accounts.deleted"
      consumer: customers-query-accounts-deleted



    - path: /relations/customers/created
      subject: "evt.htp.re.customers.created"
      consumer: customers-query-customers-created

    - path: /relations/customers/updated
      subject: "evt.htp.re.customers.updated"
      consumer: customers-query-customers-updated

    - path: /relations/customers/deleted
      subject: "evt.htp.re.customers.deleted"
      consumer: customers-query-customers-deleted