apiVersion: v1
kind: PersistentVolume
metadata:
  name: customers-query-pv
  labels:
    app: customers-query
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /pvs/customers-query-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu-2gb-nbg1-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customers-query-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: customers-query