kind: Deployment
apiVersion: apps/v1
metadata:
  name: ce-ingestor-app
spec:
  revisionHistoryLimit: 0
  replicas: 3
  selector:
    matchLabels:
      app: ce-ingestor-app
  template:
    metadata:
      labels:
        app: ce-ingestor-app
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: ce-ingestor-app
          image: ghcr.io/manuelottlik/htp-cloudevents-poc-ce-ingestor
          imagePullPolicy: Always
          resources:
            limits:
              memory: 64Mi
              cpu: 50m
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: nats-url
---
apiVersion: v1
kind: Service
metadata:
  name: ce-ingestor-service
  labels:
    app: ce-ingestor-app
spec:
  ports:
    - port: 80
      name: ce-ingestor-app
  selector:
    app: ce-ingestor-app