kind: Deployment
apiVersion: apps/v1
metadata:
  name: welcome-letter-job-app
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: welcome-letter-job-app
  template:
    metadata:
      labels:
        app: welcome-letter-job-app
    spec:
      volumes:
        - name: welcome-letter-job-pv-storage
          persistentVolumeClaim:
            claimName: welcome-letter-job-pv-claim
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: welcome-letter-job-app
          image: ghcr.io/manuelottlik/htp-welcome-letter-job
          imagePullPolicy: Always
          ports:
           - containerPort: 8081
          resources:
            limits:
              memory: 64Mi
              cpu: 50m
          volumeMounts:
            - name: welcome-letter-job-pv-storage
              mountPath: /out