apiVersion: v1
kind: Service
metadata:
  name: customers-command-service
  labels:
    app: customers-command-app
spec:
  ports:
    - port: 8088
      name: customers-command-re-middleware
  selector:
    app: customers-command-app